name: grits
channels:
  - conda-forge
dependencies:
  - cmeutils >= 1.2.0
  - ele
  - freud = 2.13.2
  - gsd >= 3.0
  - jupyterlab
  - mbuild
  - ele
  - freud
  - numpy
  - openbabel
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - python = 3.10
