name: grits
channels:
  - conda-forge
dependencies:
  - cmeutils >=1.3.0
  - ele
  - freud >=3.0
  - gsd >=3.0
  - jupyterlab
  - mbuild >=0.17.1
  - ele
  - numpy
  - openbabel
  - pip
  - pre-commit
  - py3Dmol
  - pytest
  - pytest-cov
  - python >=3.10
